apiVersion: apps/v1
kind: Deployment
metadata:
  name: tone-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tone-registry
  template:
    metadata:
      labels:
        app: tone-registry
    spec:
      containers:
        - name: tone-registry
          image: tone-registry
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: registry-manifests
              mountPath: /manifests
              readOnly: true

      volumes:
        - name: registry-manifests
          configMap:
            name: registry-manifests
