apiVersion: apps/v1
kind: Deployment
metadata:
  name: tone-inference
  labels:
    app: tone-inference
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  selector:
    matchLabels:
      app: tone-inference
  template:
    metadata:
      labels:
        app: tone-inference
    spec:
      containers:
        - name: tone-inference
          image: tone-inference:latest
          ports:
            - containerPort: 8080
          env:
            - name: REGISTRY_URL
              value: "http://tone-registry-service:80"
            - name: MODEL_NAME
              value: "tone"
            - name: MODEL_VERSION
              value: "1.0.2"
            - name: MODEL_CACHE_PATH
              value: "/cache/models"
          volumeMounts:
            - name: model-cache
              mountPath: /cache/models
      volumes:
        - name: model-cache
          emptyDir: {}
