apiVersion: v1
kind: Service
metadata:
  name: tone-inference-service
  labels:
    app: tone-inference
spec:
  selector:
    app: tone-inference
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  type: LoadBalancer
