name: Multi-Service CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Authenticate with GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker us-east1-docker.pkg.dev

      - uses: "google-github-actions/setup-gcloud@v2"
        with:
          install_components: "gke-gcloud-auth-plugin"

      - name: Get GKE credentials
        uses: google-github-actions/get-gke-credentials@v1
        with:
          cluster_name: tone-cluster
          location: us-east1-b
          project_id: tone-486901

      - name: Get GKE credentials
        run: gcloud container clusters get-credentials tone-cluster --zone us-east1-b

      - name: Build and deploy registry
        run: |
          docker buildx build --platform linux/amd64 \
            -t us-east1-docker.pkg.dev/tone-486901/tone-repo/registry:latest \
            ./services/registry --push

          kubectl create configmap registry-manifests \
            --from-file=./manifests \
            --dry-run=client -o yaml | kubectl apply -f -

          kubectl apply -f ./services/registry/k8s/

          kubectl rollout restart deployment tone-registry
